name: kaggle-agent-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # Inherit from base environment
  - python=3.9
  
  # Data manipulation and analysis
  - pandas>=1.3.0
  - numpy>=1.21.0
  
  # Machine Learning
  - scikit-learn>=1.0.0
  - lightgbm>=3.0.0
  - xgboost>=1.5.0
  
  # Optimization
  - optuna>=3.0.0
  
  # Visualization
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  
  # Utilities
  - tqdm>=4.62.0
  - pyyaml>=6.0
  - joblib>=1.1.0
  - click>=8.0.0
  
  # Development specific
  - jupyter
  - jupyterlab
  - ipykernel
  - pytest>=6.0
  - pytest-cov
  - pytest-mock
  - black
  - flake8
  - mypy
  - isort
  - pre-commit
  
  # Documentation
  - sphinx
  - sphinx-rtd-theme
  - sphinx-autodoc-typehints
  
  # Debugging
  - ipdb
  - pdbpp
  
  # Pip dependencies
  - pip
  - pip:
    # Kaggle API
    - kaggle>=1.5.12
    
    # CatBoost
    - catboost>=1.0.0
    
    # Additional dev tools
    - python-dotenv
    - bandit  # Security linting
    - safety  # Security vulnerabilities check
    - mkdocs  # Alternative documentation
    - mkdocs-material